language: csharp
mono: latest
dotnet: 2.1.401
matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
branches:
  only:
    - master
install:
  - ./build.sh -t Clean
script:
  - ./build.sh -t Tests
